# This configuration file should contain all required configuration parameters
# for the Nextclade workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values

strain_id_field: "accession"
display_strain_field: "strain"

tree:
  method: "iqtree"

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_rate: 0.0006
  # Rooting to outgroup clade based on strains
  # Pinneo-NIG-1969 (L accession KM822127 and S accession KM822128)
  # and strain 812285 (L accession MG812674 and S accession MG812675)
  # TreeTime needs two tips to root to common ancestor of these tips
  root: "mid_point"
  #  l: "KM822127 MG812674"
  #  s: "KM822128 MG812675"
  #  gpc: "KM822128"

ancestral:
  inference: "joint"

traits:
  columns: "country clade_membership lineage_name"

export:
  auspice_config: "../phylogenetic/defaults/auspice_config.json"
  description: "../phylogenetic/defaults/description.md"
